# Generated by Django 5.0 on 2024-01-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employee_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=200)),
                ('job_date', models.DateField(max_length=200)),
                ('job_review', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employer_registration')),
                ('workername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee_registration')),
            ],
        ),
    ]
