# Generated by Django 5.0 on 2024-01-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wphone', models.CharField(max_length=200)),
                ('ackmesg', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employer_registration')),
                ('workername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee_registration')),
            ],
        ),
    ]
